name: 'private registry docker action test'
description: 'private registry docker action test'
inputs:
  my-test-input:
    description: 'test'
    required: true
    default: 'okay'
  acr-secret:
    description: 'secret to acr'
    required: true
runs:
  using: "composite"
  steps:
    - name: mask secret
      run: echo "::add-mask::${{ inputs.acr-secret }}"
      shell: bash
    - name: auth to acr
      shell: bash
      run: echo ${{ inputs.acr-secret }} | docker login --username test123j --password-stdin test123j.azurecr.io
    - name: prepare the folder for the second action otherwise have to hardcode ref in folder path
      run: | 
        mkdir -p ./__tmp/the-actual-private-docker-action
        action=$(find ${{ github.action_path }} -path "*/the-actual-private-docker-action/action.yml")
        echo "action is in this path: $action"
        cp $action ./__tmp/the-actual-private-docker-action/action.yml
        echo "copied to ./__tmp/the-actual-private-docker-action/action.yml"
      shell: bash
    - name: run the second composite action
      uses: ./__tmp/the-actual-private-docker-action
      with:
        who-to-greet: ${{ inputs.my-test-input }}
