name: 'private registry docker action test'
description: 'private registry docker action test'
inputs:
  my-test-input:
    description: 'test'
    required: true
    default: 'okay'
runs:
  using: "composite"
  steps:
    - uses: joshjohanning-org/simple-docker-action/private@main
