name: 'private registry docker action test'
description: 'private registry docker action test'
inputs:
  password:  
    required: true
    description: acr password
runs:
  using: "composite"
  steps:
    - name: back up docker creds
      run: cp ${{ runner.workspace }}/../../.docker/config.json ${{ runner.workspace }}/../../.docker/config.json.bak
      id: docker-backup
      shell: bash
    - name: auth to acr
      run: echo ${{ inputs.password }} | docker login --username test123j --password-stdin test123j.azurecr.io
      shell: bash

    # get and output path to composite action
    - uses: joshjohanning-org/composite-action-private-registry-docker-actions/nested-composite-action-better/2-get-path@main
      id: composite-path

    # copy composite action to tmp folder - the action-implementation folder is where you define what docker action to reference
    - run: |
        mkdir -p __tmp
        cp -r '${{ steps.composite-path.outputs.path }}/3-action-implementation' __tmp/action-implementation
      shell: bash

    # run the local composite action w/ docker private registry
    - uses: ./__tmp/action-implementation

    - run: rm -rf __tmp/action-implementation
      name: cleanup action
      shell: bash
      if: always()

    - run: mv ${{ runner.workspace }}/../../.docker/config.json.bak ${{ runner.workspace }}/../../.docker/config.json
      name: restore original docker creds
      shell: bash
      if: always() && steps.docker-backup.conclusion == 'success'

    - run: cat ${{ runner.workspace }}/../../.docker/config.json
      name: print docker registries
      shell: bash
      if: always() && steps.docker-backup.conclusion == 'success'
